version: '3'

services:
  sma-query:
    image: froschie/sma-query:latest
    volumes:
      - ./config_measurements.json:/config_measurements.json
      - ./config_queries.json:/config_queries.json
    environment:
      influx_ip: influx
      influx_port: 8086
      influx_db: sma
      influx_user: ee
      influx_pw: "${INFLUX_PW}"
      sma_ip: "${SMA_INVERTER_IP}"
      sma_pw: "${SMA_INVERTER_PASSWORD}"
      sma_mode: https
      interval: 15
      write: 1
      TZ: Europe/Stockholm
      log: INFO
    logging:
      driver: "json-file"
      options:
        max-size: "5M"
        max-file: "10"
    restart: unless-stopped
    depends_on:
      - influx
    links:
      - influx

  influx:
    image: influxdb:1.8.10
    volumes:
      - ./influx-storage:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
    environment:
      INFLUXDB_DB: sma
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: "${INFLUXDB_ADMIN_PASSWORD}"
      INFLUXDB_USER: ee
    ports:
      - "8086:8086"
    logging:
      driver: "json-file"
      options:
        max-size: "5M"
        max-file: "10"
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana-oss:latest
    environment:
      - GF_INSTALL_PLUGINS=fetzerch-sunandmoon-datasource
    volumes:
      - ./grafana-storage:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "5M"
        max-file: "10"
    depends_on:
      - influx

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.20.30.0/24
        gateway: 10.20.30.1
